version: '3'
services:
  db:
    container_name: chatdb
    build: ./services/mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin1
      - MYSQL_DATABASE=chatapp
      - MYSQL_USER=medz
      - MYSQL_PASSWORD=admin2
      - TZ=UTC
    command: [--default-authentication-plugin=mysql_native_password]
    ports:
      - '3306:3306'
  app:
    container_name: chatapp
    build: ./app
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  counter:
    container_name: counterapp
    build: ./workers/counter
    command: bash -c "cron && bundle exec puma -p 3001"
    volumes:
      - ./workers/counter:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
      